version: '3'

services:
  # Backend Django (API REST)
  rest_api:
    build:
      context: ../python  # Ruta al contexto del Dockerfile para Django
    command: gunicorn drf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../python/django:/app   # Monta el directorio de la app Django
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
  
  # MySQL Database
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password   # Cambia la contraseña de root
      MYSQL_DATABASE: diseno              # Nombre de la base de datos
      MYSQL_USER: user                    # Nombre del usuario
      MYSQL_PASSWORD: password            # Contraseña del usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql         # Persistencia de los datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "3306"  # Para permitir la exportación de métricas internas

  # Redis Service
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Monta el archivo de configuración de Prometheus
    ports:
      - "9090:9090"  # Puerto de Prometheus
    links:
      - redis-exporter
      - mysqld-exporter
      - rest_api

  # Redis Exporter for Prometheus
  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"  # Puerto del Redis Exporter para Prometheus

  # MySQL Exporter for Prometheus
  mysqld-exporter:
    image: prom/mysqld-exporter:v0.12.1
    environment:
      - DATA_SOURCE_NAME=user:password@(mysql:3306)/diseno
    ports:
      - "9104:9104"  # Puerto del MySQL Exporter para Prometheus
    links:
      - mysql
    depends_on:
      - mysql
    restart: always  # Reinicia el exporter si no puede conectarse a MySQL    

volumes:
  mysql_data:
  redis_data:
