version: '3'

services:

  #REST_API:
  # build: ../REST_API

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password   # Cambia la contraseña del root
      MYSQL_DATABASE: diseño              # Nombre de la base de datos inicial
      MYSQL_USER: user                    # Nombre del usuario
      MYSQL_PASSWORD: password        # Contraseña del usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql       # Persistencia de datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  
  
  #redis:
   # image: redis:7.2-alpine  # Imagen de Redis basada en Alpine
    #ports:
     # - "6379:6379"          # Mapea el puerto 6379 del contenedor al puerto 6379 del host
    #volumes:
     # - redis_data:/data     # Volumen persistente para los datos de Redis

volumes:
  mysql_data:
 # redis_data:


