global:
  scrape_interval: 15s  # Intervalo de recolección de métricas
  evaluation_interval: 15s  # Intervalo de evaluación de reglas

scrape_configs:

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # MySQL Exporter
  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  # Django Application 
  - job_name: 'django-app'
    static_configs:
      - targets: ['rest_api:8001']  # Si hay un endpoint para métricas de Django
