"""
Django settings for drf project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-25*f33%^xi#3f+^^l8j*3dmp66$oti*9_$le=si_1=-n4c8y9)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.PrometheusMiddleware',
]

ROOT_URLCONF = 'drf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'diseno',  # Reemplaza con el nombre de tu base de datos
        'USER': 'user',      # Reemplaza con tu nombre de usuario
        'PASSWORD': 'password',  # Reemplaza con tu contraseña
        'HOST': 'mysql',  # O la dirección IP del servidor MySQL
        'PORT': '3306',       # Puerto por defecto de MySQL
    },
    'pool': {
        'ENGINE': 'mysql.connector.django',  # Conexión con pool
        'NAME': 'diseno',  # Reemplaza con el nombre de tu base de datos
        'USER': 'user',      # Reemplaza con tu nombre de usuario
        'PASSWORD': 'password',  # Reemplaza con tu contraseña
        'HOST': 'mysql',  # O la dirección IP del servidor MySQL
        'PORT': '3306',       # Puerto por defecto de MySQL
        'OPTIONS': {
            'pool_name': 'mypool',
            'pool_size': 10,  # Tamaño del pool de conexiones
            'pool_reset_session': True,  # Restablece la sesión después de usar
        },
    }
}


"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'products',  # Reemplaza con el nombre de tu base de datos
        'USER': 'root',      # Reemplaza con tu nombre de usuario
        'PASSWORD': 'Karc2809..',  # Reemplaza con tu contraseña
        'HOST': 'localhost',  # O la dirección IP del servidor MySQL
        'PORT': '3306',       # Puerto por defecto de MySQL
    },
    'pool': {
        'ENGINE': 'mysql.connector.django',  # Conexión con pool
        'NAME': 'products',  # Reemplaza con el nombre de tu base de datos
        'USER': 'root',      # Reemplaza con tu nombre de usuario
        'PASSWORD': 'Karc2809..',  # Reemplaza con tu contraseña
        'HOST': 'localhost',  # O la dirección IP del servidor MySQL
        'PORT': '3306',       # Puerto por defecto de MySQL
        'OPTIONS': {
            'pool_name': 'mypool',
            'pool_size': 10,  # Tamaño del pool de conexiones
            'pool_reset_session': True,  # Restablece la sesión después de usar
        },
    }
}
"""
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379/0',  # Cambia el número si necesitas usar otra base de datos en Redis 
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
